-- 1
--a
SELECT * FROM PROIZVODITELI 
WHERE GRAD_P IN ('Skopje', 'Bitola');

--b
SELECT ISP# FROM PONUDI 
WHERE DEL# = 5 AND PR# = 1;

--v
SELECT DEL# FROM PONUDI, DELOVI 
WHERE PONUDI.ISP# = 8 AND DELOVI.DEL# = PONUDI.DEL#;

--g
SELECT PONUDI.DEL# FROM PONUDI, PROIZVODITELI 
WHERE PONUDI.PR# = PROIZVODITELI.PR# AND PROIZVODITELI.GRAD_P = 'Bitola';

--d
SELECT PONUDI.DEL# FROM PONUDI, PROIZVODITELI, ISP 
WHERE PONUDI.PR# = PROIZVODITELI.PR# AND ISP.ISP# = PONUDI.ISP# AND PROIZVODITELI.GRAD_P = ISP.GRAD_I

--2
--a
SELECT VRABOTENI.IME_VRAB, SEKTORI.IME_SEKOR 
FROM VRABOTENI, SEKTORI 
WHERE VRABOTENI.KVALIFIKACIJA = 'VKV' AND VRABOTENI.PLATA > 10000 AND VRABOTENI.SEKTOR# = SEKTORI.SEKTOR#
ORDER BY VRABOTENI.IME_VRAB

--b
SELECT VRABOTENI.IME_VRAB 
FROM VRABOTENI JOIN SEKTORI ON VRABOTENI.SEKTOR# = SEKTORI.SEKTOR# 
WHERE SEKTORI.GRAD = 'Skopje';

--v
SELECT SEKTORI.IME_SEKOR, VRABOTENI.KVALIFIKACIJA 
FROM SEKTORI NATURAL JOIN VRABOTENI GROUP BY SEKTORI.IME_SEKOR, VRABOTENI.KVALIFIKACIJA; 

--g
SELECT IME_VRAB FROM SEKTORI WHERE SEKTOR# IN (4,7);

--d
SELECT SEKTOR# FROM SEKTORI MINUS SELECT DISTINCT(SEKTOR#) FROM VRABOTENI

--gj
SELECT VRABOTENI.VRAB# FROM VRABOTENI NATURAL JOIN UCESTVUVA WHERE VRABOTENI.KVALIFIKACIJA = 'VKV';
SELECT UCESTVUVA.VRAB# FROM UCESTVUVA WHERE VRAB# IN (SELECT VRAB# FROM VRABOTENI WHERE KVALIFIKACIJA='VKV');

--e
SELECT AVG(PLATA) FROM VRABOTENI WHERE KVALIFIKACIJA = 'VKV';

--zh
SELECT COUNT((DISTINCT FUNKCIJA)) FROM UCESTVUVA WHERE UCESTVUVA.VRAB# = 964

--3
--3.1
SELECT imePr, nabCena, prodCena * (1-0.18) FROM PROIZVOD;

--3.2
SELECT imePr, nabCena, prodCena, (prodCena-nabCena) as razlika FROM PROIZVOD;

--3.3
SELECT * FROM PROIZVOD WHERE imePr LIKE 'Maslo%'

--3.4
SELECT * FROM PROIZVOD WHERE edMer IN ('lit','kgr');

--3.5
SELECT * FROM PROIZVOD WHERE prodCena BETWEEN 50 AND 250;

--4
--4.1
SELECT * FROM ORDERS WHERE PARTNUM IN (SELECT PARTNUM FROM PART WHERE DESCRIPTION LIKE 'ROAD%');

--4.2
SELECT (AVG ORDERS.QUANTITY * PART.PRICE) FROM ORDERS NATURAL JOIN PART

--4.3
SELECT NAME, ORDEREDON FROM ORDERS NATURAL JOIN PART WHERE ORDERS.QUANTITY * PART.PRICE > 
(SELECT (AVG ORDERS.QUANTITY * PART.PRICE) FROM ORDERS NATURAL JOIN PART)

--4.4
SELECT ORDERS.NAME, AVG(ORDERS.QUANTITY * PART.PRICE) FROM ORDERS NATURAL JOIN PART GROUP BY ORDERS.NAME

--4.5
SELECT ORDERS.NAME, AVG(ORDERS.QUANTITY * PART.PRICE) AS VKUPEN_IZNOS FROM ORDERS NATURAL JOIN PART 
GROUP BY ORDERS.NAME
HAVING VKUPEN_IZNOS > (SELECT AVG(ORDERS.QUANTITY * PART.PRICE) FROM ORDERS NATURAL JOIN PART);

--4.6
SELECT ORDERS.PARTNUM, COUNT(*), SUM(ORDERS.QUANTITY * PART.PRICE) AS PROSECEN_IZNOS 
FROM ORDERS AS O NATURAL JOIN PART
HAVING PROSECEN_IZNOS > (SELECT  SUM(ORDERS.QUANTITY * PART.PRICE) FROM ORDERS NATURAL JOIN PART AS P WHERE P.PARTNUM = O.PARTNUM )

